.TH 4DIGITS "6" "Nov 2011" "4digits 1.1" "The 4digits game"
.SH NAME
4digits \- Guess-the-number Puzzle Game
.SH SYNOPSIS
.B 4digits

.B 4digits-text
[\fIOPTION\fR] ...
.SH DESCRIPTION
4digits is a guess-the-number puzzle game. It's called Bulls and Cows,
and in China people simply call it Guess-the-Number. The game's
objective is to guess a four-digit number in 8 times using as less
time as possible. It is similar to Mastermind, but the four digits
are different to each other. 4digits has both graphical user
interface version and text user interface version.
.B 4digits
launches the graphical version, and
.B 4digits-text
launches the text version.
.SH OPTIONS
These options only apply to the text interface.
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information and exit
.SH AUTHOR
Written by Yongzhi Pan.
.SH "REPORTING BUGS"
Report bugs at <https://github.com/fossilet/4digits/issues>.
.SH COPYRIGHT
Copyright \(co 2004-2012 Yongzhi Pan.
.br
This is Free Software; this software is licensed under the GPL version
2, as published by the Free Software Foundation.  There is NO warranty;
not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
The full documentation of this game is in HTML format shipped with the game.
